import type { Metadata } from "next";
import { Inter, Poppins, Space_Grotesk,Roboto_Mono, Montserrat, Lora } from "next/font/google";
import "./globals.css";
import SocialLinksFloating from "@/components/SocialLinksFloating";
import SocialLinksVertical from "@/components/SocialLinksVertical";
import Header from "@components/Header";
import { ThemeProvider } from "next-themes";

const mont = Montserrat({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-mont',
})
const roboto = Roboto_Mono({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto',
})
const lora = Lora({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-lora',
})
const space = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-space",
});

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  weight: ['400', '500', '600', '700'],
})

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`min-h-screen transition-colors duration-2000 ease-in-out ${poppins.variable} ${space.variable} ${inter.variable} ${lora.variable}`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="default"
          enableSystem={false}
          themes={["default", "light"]}
        >
          <Header />
          {children}
          {/* XL screens */}
          <div className="hidden xl:block">
            <SocialLinksVertical />
          </div>

          {/* Mid screens */}
          <SocialLinksFloating />


        </ThemeProvider>
      </body>
    </html>
  );
}
